params:
  xgboost:
    default:
      random_state: 42
      objective: binary:logistic
      n_estimators: 250
      n_jobs: -1
      learning_rate: 0.05
    dataset_configs:
      amlsim_201:
        random_state: 42
        objective: binary:logistic
        n_estimators: 500
        n_jobs: -1
        learning_rate: 0.05
        scale_pos_weight: 4.

  lightgbm:
    default:
      random_state: 42
      num_leaves: 256
      learning_rate: 0.05
      n_estimators: 250
      n_jobs: -1
      boosting_type: gbdt
    dataset_configs:
      amlsim_31:
        random_state: 111
        num_leaves: 222
        learning_rate: 0.031
        n_estimators: 677
        is_unbalance: false
        subsample: 0.264
        colsample_bytree: 0.117
        n_jobs: -1
        min_data_in_leaf: 11
        boosting_type: gbdt
        class_weight:
          0: 0.746
          1: 0.254
      amlsim_51:
        random_state: 111
        num_leaves: 107
        learning_rate: 0.08
        n_estimators: 671
        n_jobs: -1
        boosting_type: dart
        is_unbalance: false
      amlsim_201:
        random_state: 42
        num_leaves: 256
        learning_rate: 0.05
        n_estimators: 250
        n_jobs: -1
        boosting_type: gbdt
        class_weight:
          0: 0.2
          1: 0.8
